aliases: []
creation_timestamp: 1713375853851
current_stage: None
description: ''
last_updated_timestamp: 1713375853851
name: iris_spieces_prediction_experimentations
run_id: 1805ae190fc04de98c9344864897ae61
run_link: ''
source: file:///G:/Innomatics%20Internship/Task%20-%20%20Experiment%20Tracking%20and%20Model%20Management/mlruns/338614161403077691/1805ae190fc04de98c9344864897ae61/artifacts/best_estimator
status: READY
status_message: null
storage_location: file:///G:/Innomatics%20Internship/Task%20-%20%20Experiment%20Tracking%20and%20Model%20Management/mlruns/338614161403077691/1805ae190fc04de98c9344864897ae61/artifacts/best_estimator
user_id: null
version: 1
