aliases: []
creation_timestamp: 1713456253310
current_stage: Staging
description: ''
last_updated_timestamp: 1713457942566
name: iris_spieces_prediction_experimentations
run_id: b3a3fa57af804924891dd64e0a3d783f
run_link: ''
source: file:///G:/Innomatics%20Internship/Task%20-%20%20Experiment%20Tracking%20and%20Model%20Management/mlruns/338614161403077691/b3a3fa57af804924891dd64e0a3d783f/artifacts/best_estimator
status: READY
status_message: null
storage_location: file:///G:/Innomatics%20Internship/Task%20-%20%20Experiment%20Tracking%20and%20Model%20Management/mlruns/338614161403077691/b3a3fa57af804924891dd64e0a3d783f/artifacts/best_estimator
user_id: null
version: 5
