aliases: []
creation_timestamp: 1713456168602
current_stage: Production
description: ''
last_updated_timestamp: 1713457832460
name: iris_spieces_prediction_experimentations
run_id: 0319b2480605465bbb24e5fb1791b0ec
run_link: ''
source: file:///G:/Innomatics%20Internship/Task%20-%20%20Experiment%20Tracking%20and%20Model%20Management/mlruns/338614161403077691/0319b2480605465bbb24e5fb1791b0ec/artifacts/best_estimator
status: READY
status_message: null
storage_location: file:///G:/Innomatics%20Internship/Task%20-%20%20Experiment%20Tracking%20and%20Model%20Management/mlruns/338614161403077691/0319b2480605465bbb24e5fb1791b0ec/artifacts/best_estimator
user_id: null
version: 2
